#!/usr/bin/python
"""prepare initail and boundray for real.exe

Just for run grib_prep.pl and wrfprep.pl

This is script for NCEP REANALYSIS 2 as INPUTDATA case"""


import os
import commands
import glob
import sys
#import string


#----------------------------------------------------------
# main parameters : case name , time setting , directorys 
#----------------------------------------------------------
casename  = 'CFS'
time_begin = '1982120200'
time_end   = '1983050100'
time_intv_hr = '3'  #hour

wrfroot = '/cfs/scratch/users/xingyuan/MRED'
wrfsi_root=wrfroot+'/wrfsi'
moad_dir = wrfsi_root+'/domains/USA'
run_dir  = wrfsi_root + '/etc'
Vtable_dir  = wrfsi_root + '/extdata/static'
Vtable_fn   = 'Vtable.' + casename
gp_out_dir  = wrfsi_root + '/extdata/extprd'
gp_log_dir  = wrfsi_root + '/extdata/log'

os.environ['INSTALLROOT'] = wrfsi_root
os.environ['MOAD_DATAROOT'] = moad_dir

si_nl_dir = moad_dir + '/static'
si_nl_name = 'wrfsi.nl.'+casename
si_out_dir = moad_dir + '/siprd'
si_log_dir = moad_dir + '/log'

si_case_out_dir = si_out_dir + '/' + casename + '.'+ time_begin

#nco_root = '/opt/nco/3.1.6/bin'

time_intv_sec = str(int(time_intv_hr) * 60 * 60)

# you should compile source code under wrfzsb_dir before run this python script
wrfzsb_dir= wrfsi_root+'/wrfzsb'

#------------  run grib_prep.pl ----------------------------
os.chdir(Vtable_dir)
filestr='''&filetimespec
START_YEAR  = startyear,
START_MONTH = startmonth,
START_DAY   = startday,
START_HOUR  = starthour,
START_MINUTE= 00,
START_SECOND= 00,
END_YEAR  = endyear,
END_MONTH = endmonth,
END_DAY   = endday,
END_HOUR  = endhour,
END_MINUTE= 00,
END_SECOND= 00,
INTERVAL  = time_intv_sec,
/
&gpinput_defs
 SRCNAME = 'CFS'
 SRCVTAB = 'CFS'
 SRCPATH = '/cfs/scratch/users/xingyuan/MRED/data/1982/19821202',
 SRCCYCLE = 3, 3 , 3,
 SRCDELAY = 0, 0 , 0,
/'''

filestr =filestr.replace('startyear',time_begin[0:4])
filestr =filestr.replace('startmonth',time_begin[4:6])
filestr =filestr.replace('startday',time_begin[6:8])
filestr =filestr.replace('starthour',time_begin[8:10])
filestr =filestr.replace('endyear',time_end[0:4])
filestr =filestr.replace('endmonth',time_end[4:6])
filestr =filestr.replace('endday',time_end[6:8])
filestr =filestr.replace('endhour',time_end[8:10])
filestr =filestr.replace('time_intv_sec',time_intv_sec)
filestr =filestr.replace('NRA2',casename)
filestr =filestr.replace('wrfroot',wrfroot)

f = open('grib_prep.nl','w')
f.write(filestr)
f.close()

os.chdir(run_dir)
print ' time ./grib_prep.pl -s '+time_begin+' -e '+time_end+' -t '+time_intv_hr+' '+casename
os.system('time ./grib_prep.pl -s '+time_begin+' -e '+time_end+' -t '+time_intv_hr+' '+casename)
os.chdir(gp_log_dir)
os.system('tail gp_'+casename+'.'+time_begin+'.log')
os.chdir(gp_out_dir)
os.system('ls -l '+casename+'*')
#-------------------------------------------------------------
# run wrfsi.pl
#-------------------------------------------------------------
os.chdir(si_nl_dir)
filestr='''&project_id
 SIMULATION_NAME = 'UIUC 30km U.S. Domain <Ter_m>'
 USER_DESC = 'UIUC/ISWS'
/
&filetimespec
 START_YEAR = startyear,
 START_MONTH = startmonth,
 START_DAY = startday,
 START_HOUR = starthour,
 START_MINUTE = 00,
 START_SECOND = 00,
 END_YEAR = endyear,
 END_MONTH = endmonth,
 END_DAY = endday,
 END_HOUR = endhour,
 END_MINUTE = 00,
 END_SECOND = 00,
 INTERVAL = time_intv_sec,
/
&hgridspec
 NUM_DOMAINS = 1
 XDIM = 196,
 YDIM = 139,
 PARENT_ID = 1,
 RATIO_TO_PARENT = 1,
 DOMAIN_ORIGIN_PARENT_X = 1,
 DOMAIN_ORIGIN_PARENT_Y = 1,
 MAP_PROJ_NAME = 'lambert',
 LATLON_GRID = 'User_defined_grid_NOT_in_use',
 MOAD_KNOWN_LAT = 37.5,
 MOAD_KNOWN_LON = -95.5,m
 MOAD_KNOWN_LOC = 'center',
 MOAD_STAND_LATS = 30.0, 60.0,
 MOAD_STAND_LONS = -95.5,
 MOAD_DELTA_X = 30000.,
 MOAD_DELTA_Y = 30000.,
 SILAVWT_PARM_WRF = 0.,
 TOPTWVL_PARM_WRF = 4.,
/
&sfcfiles
 TOPO_30S = 'wrfsi_root/extdata/GEOG/topo_30s',
 LANDUSE_30S = 'wrfsi_root/extdata/GEOG/landuse_30s',
 SOILTYPE_TOP_30S = 'wrfsi_root/extdata/GEOG/soiltype_top_30s',
 SOILTYPE_BOT_30S = 'wrfsi_root/extdata/GEOG/soiltype_bot_30s',
 GREENFRAC = 'wrfsi_root/extdata/GEOG/greenfrac',
 SOILTEMP_1DEG = 'wrfsi_root/extdata/GEOG/soiltemp_1deg',
 ALBEDO_NCEP = 'wrfsi_root/extdata/GEOG/albedo_ncep',
 MAXSNOWALB = 'wrfsi_root/extdata/GEOG/maxsnowalb',
 ISLOPE = 'wrfsi_root/extdata/GEOG/islope',
/
&interp_control
 NUM_DOMAINS = 1,
 DOMAIN_ID_LIST = 1,
 PTOP_PA = 1000,
 HINTERP_METHOD = 1,
 LSM_HINTERP_METHOD = 0,
 NUM_INIT_TIMES = 1,
 INIT_ROOT = 'NRA2',
 LBC_ROOT = 'NRA2',
 LSM_ROOT = 'NRA2',
 CONSTANTS_FULL_NAME ='',
 VERBOSE_LOG = .false.,
 OUTPUT_COORD = 'ETAP',
 LEVELS = 1.0000, 0.9909, 0.9818, 0.9636, 0.9364,
        0.9000, 0.8636, 0.8182, 0.7727, 0.7273,
        0.6818, 0.6364, 0.5909, 0.5455, 0.5000,
        0.4545, 0.4091, 0.3636, 0.3182, 0.2727,
        0.2273, 0.1818, 0.1414, 0.1061, 0.0707,
        0.0455, 0.0253, 0.0101, 0.0000,
 OUTPUT_VARS = 2,
 OUTPUT_FILE_TYPE = 'BIN',
/
&si_paths
 ANALPATH = 'gp_out_dir',
 LBCPATH = 'gp_out_dir',
 LSMPATH = 'gp_out_dir',
 CONSTANTS_PATH = 'gp_out_dir',
/'''

filestr =filestr.replace('startyear',time_begin[0:4])
filestr =filestr.replace('startmonth',time_begin[4:6])
filestr =filestr.replace('startday',time_begin[6:8])
filestr =filestr.replace('starthour',time_begin[8:10])
filestr =filestr.replace('endyear',time_end[0:4])
filestr =filestr.replace('endmonth',time_end[4:6])
filestr =filestr.replace('endday',time_end[6:8])
filestr =filestr.replace('endhour',time_end[8:10])
filestr =filestr.replace('time_intv_sec',time_intv_sec)
filestr =filestr.replace('gp_out_dir',gp_out_dir)
filestr =filestr.replace('casename',casename)
filestr =filestr.replace('NRA2',casename)
filestr =filestr.replace('wrfsi_root',wrfsi_root)

f = open ('wrfsi.nl','w')
f.write(filestr)
f.close()
os.chdir(run_dir)
os.system('time ./wrfprep.pl -T '+casename)
